
name: Run fetchdatatosql.py Daily

on:
  schedule:
    - cron: '0 23 * * 1-5' # Runs daily at 23:00 UTC except on weekends
  workflow_dispatch:

jobs:
  execute-script:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}
        ports:
          -  "5432:5432"
        options: >-
          --health-cmd "pg_isready -U ${{ secrets.DATABASE_USER }}" 
          --health-interval=10s
          --health-timeout 5s
          --health-retries 5 
    
    env:
      DATABASE_HOST: localhost
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}


    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U ${{ secrets.DATABASE_USER }}; do
            echo "Waiting for PostgreSQL to be available..."
            sleep 2
          done

      - name: Run fetchdatatosql.py
        run: python fetchdatatosql.py