
name: Run fetchdatatosql.py Daily

on:
  schedule:
    - cron: '0 23 * * 1-5' # Runs daily at 23:00 UTC except on weekends
  workflow_dispatch:

jobs:
  execute-script:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Lorenzo_22
          POSTGRES_DB: Personal_Shares
        ports:
          - "5432:5432"
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5 
    
    env:
      DATABASE_HOST: localhost
      DATABASE_NAME: Personal_Shares
      DATABASE_USER: postgres
      DATABASE_PASSWORD: Lorenzo_22
      DATABASE_PORT: 5432

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p ${{ env.DATABASE_PORT }}; do
            sleep 1
          done

      - name: Setup Database
        run: |
          psql -h localhost -U postgres -d Personal_Shares -c "CREATE TABLE IF NOT EXISTS stock_prices_actions (
            id SERIAL PRIMARY KEY,
            stock_symbol VARCHAR(10),
            date DATE,
            close_price DECIMAL,
            volume NUMERIC
          );"
        env:
          PGPASSWORD: ${{ env.DATABASE_PASSWORD }}

      - name: Run fetchdatatosql.py
        run: python fetchdatatosql.py
        env:
          DATABASE_HOST: ${{ env.DATABASE_HOST }}
          DATABASE_NAME: ${{ env.DATABASE_NAME }}
          DATABASE_USER: ${{ env.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ env.DATABASE_PASSWORD }}
          DATABASE_PORT: ${{ env.DATABASE_PORT }}